os:
  - linux
  - osx
  - windows
language: node_js
install:
  - npm ci
  - npm install -g codecov
node_js:
  - "node"
after_script:
  - codecov
notifications:
  webhooks: https://coveralls.io/webhook